nodejs-week1
Sana-Shabeel/hyf-homework pull request #15
Opened 2022-02-21 14:32 UTC by Sana-Shabeel

2022-02-23 23:58 UTC, shpomp commented
Will review in the upcoming days :)

2022-02-24 00:09 UTC, shpomp commented on nodejs/week1/homework/warmup.js
> +
Clean, clear, correct. 👌🏽  👏🏽  ✨ 

Consideration for improvements:

- We are getting some crazy fractions for circumference and area. Perhaps would make sense to round the numbers? 
- `Math.PI * this.radius ** 2` is perfectly fine, but for readability and practice `Math.pow()` could be tried out to perform one of the operations here.

2022-02-25 21:16 UTC, shpomp commented
Good job overall!  👏🏽 
However, the reviews and the random fetches threw this off a little. 
Try to fix it and message me if any questions!
For the fetching of the random meals/reservations, the tets are misleading as they pass, while they should fail. I will inform somebody who can correct that :)

2022-02-28 21:41 UTC, shpomp requested changes

2022-02-28 22:21 UTC, Sana-Shabeel commented on nodejs/week1/homework/src/backend/app.js
> +
Roger that. I will make the changes tomorrow

2022-03-01 11:20 UTC, Sana-Shabeel commented on nodejs/week1/homework/src/backend/app.js
> +
i made the changes you recommended.

2022-03-01 11:33 UTC, shpomp commented on nodejs/week1/homework/src/backend/app.js
> +});
meal.reviews

2022-03-01 12:13 UTC, Sana-Shabeel commented on nodejs/week1/homework/src/backend/app.js
> +});
DONE. 
can i merge now ?

2022-03-01 13:16 UTC, merged