nodejs-week2
Sana-Shabeel/hyf-homework pull request #16
Opened 2022-03-02 02:06 UTC by Sana-Shabeel

2022-03-05 22:06 UTC, shpomp commented
Good job overall! 🤩 
However, there are quite a few inconsistencies and some tasks not fully done. 
It is good that you are efficient and have more time to study after early HW submission, on the other hand, perhaps it would be beneficial to take a day or 2 longer but be much more thorough and consistent with the tasks. You are doing great and clearly have a very good grasp 💪🏽 , just a little rushed 🏃🏽 

This part of the homework is more or less overlooked:
> What if there is no meal with the requested id in meals.json?
> What if the users writes a string as id? fx "/api/meals/lol"
> What if the users write a query parameter that is not supported?

To summarize the specific comments, the returns and checks for user errors are quite inconsistent. In some cases, you don't check for those, in some you do, but then send different types of responses to client. I would ask you to review all of the endpoints and make sure the handling is there and it is consistent. 
And the `multiply` endpoint from warmup needs some love 🤓 

Once again, good job and good progress 👏🏽 , just some more attention to detail and consistency and it will be flawless 🏅  ⭐

2022-03-05 22:07 UTC, shpomp requested changes

2022-03-06 10:55 UTC, Sana-Shabeel commented on nodejs/week2/homework/meal-sharing/src/backend/api/reservations-router.js
> +    if (req.params.id * 1 > reservations.length) {
converts to a number

2022-03-06 10:59 UTC, Sana-Shabeel commented on nodejs/week2/homework/meal-sharing/controllers/mealsController.js
> +    return res.status(400).send("Invalid limit");
Thank you very much for the detailed review, i will. implement all the changes you suggested soon and also the not rushing part. the only reason i did that was to have time for side projects i was working on.

2022-03-06 11:16 UTC, shpomp commented on nodejs/week2/homework/meal-sharing/src/backend/api/reservations-router.js
> +    if (req.params.id * 1 > reservations.length) {
I see, thanks!
Number() or parseInt() would be the way to go here.

2022-03-06 11:17 UTC, shpomp commented on nodejs/week2/homework/meal-sharing/controllers/mealsController.js
> +    return res.status(400).send("Invalid limit");
Understandable and great you are taking the initiative to do extra projects 💪🏽

2022-03-10 05:53 UTC, merged